---
- name: Setup device for development
  hosts: all
  become: false

  tasks:
    - name: Print the ansible user
      ansible.builtin.debug:
        msg: The ansible user is {{ ansible_user }}

  roles:
    - role: geerlingguy.git
      become: true

    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user }}"
          oh_my_zsh:
            plugins:
              - git
              - sudo
              - node
              - docker
              - python
            update_mode: reminder

    # Enable this when not using WSL2
    - role: geerlingguy.docker
      become: true
      docker_users:
        - "{{ ansible_user }}"

    - role: markosamuli.asdf
      vars:
        asdf_plugins:
          - name: python
          - name: nodejs

    - role: gantsign.visual-studio-code
